import "./styles/globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Inspirational Quote Generator",
  description:
    "Built by Tiffany. Generated by create-next-app. Inspired by BrianHHough",
  keywords: ["Next.js", "React", "Typescript"],
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
