import "@/styles/globals.css";

import type { Metadata } from "next";

import { Amplify, API, Auth, withSSRContext } from "aws-amplify";
import awsExports from "@/src/aws-exports";

Amplify.configure({ ...awsExports, ssr: true });

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Inspirational Quote Generator",
  description:
    "Built by tt954. Generated by create-next-app. Inspired by BrianHHough",
  keywords: ["Next.js", "React", "Typescript"],
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
